### ISSUE TITLE
How do I replace the logo with my own?

### ISSUE THREAD

**Issue by albertpeiro** [jteplitz602/Countdown#1]
Hey @jteplitz602 this is awesome! How do I customize it with my own logo?
I'm organising a hackathon on monday and I'd love to show this off!

Thanks

**Comment by jteplitz602** [comment]
Wow it's been a while since I worked on this. I believe you need to feed your logos into digify.jar (I'm not entirely sure how but try running it and seeing if it asks for input?).

It'll output two objects. Copy entities into countdown-entities.js and copy colors into countdown-colors.js and you should be good to go.

**Comment by albertpeiro** [comment]
Thanks a lot Jason! Finally got it to work just executing the .jar. Then
replaced logos.

It doesn't seem to use all colors past a certain amount of them. But still
excellent hack! :)

Thanks for your prompt response, this will look cool in some screens for
the day.

http://albertpeiro.github.io/Countdown/

On 16 April 2016 at 00:37, Jason Teplitz <notifications@github.com> wrote:

> Wow it's been a while since I worked on this. I believe you need to feed
> your logos into digify.jar (I'm not entirely sure how but try running it
> and seeing if it asks for input?).
>
> It'll output two objects. Copy entities into countdown-entities.js and
> copy colors into countdown-colors.js and you should be good to go.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jteplitz602/Countdown/issues/1#issuecomment-210685231>
>



-- 
*Albert Peiró*
